action_maps: dict[str, dict[str, str]] = {
    'knights_archers_zombies_v10': {
        '0': 'Front',
        '1': 'Back',
        '2': 'Left',
        '3': 'Right',
        '4': 'Attack',
        '5': 'None',
    },
    'pistonball_v6': {
        # continuous action space; no mapping
    },
    'cooperative_pong_v5': {
        '0': 'None',
        '1': 'Up',
        '2': 'Down',
    },
    'BattleZone-v5': {
        '0': 'None',
        '1': 'Fire',
        '2': 'Up',
        '3': 'Right',
        '4': 'Left',
        '5': 'Down',
        '6': 'Up Right',
        '7': 'Up Left',
        '8': 'Down Right',
        '9': 'Down Left',
        '10': 'Up Fire',
        '11': 'Right Fire',
        '12': 'Left Fire',
        '13': 'Down Fire',
        '14': 'Up Right Fire',
        '15': 'Up Left Fire',
        '16': 'Down Right Fire',
        '17': 'Down Left Fire',
    },
    'Berzerk-v5': {
        '0': 'None',
        '1': 'Fire',
        '2': 'Up',
        '3': 'Right',
        '4': 'Left',
        '5': 'Down',
        '6': 'Up Right',
        '7': 'Up Left',
        '8': 'Down Right',
        '9': 'Down Left',
        '10': 'Up Fire',
        '11': 'Right Fire',
        '12': 'Left Fire',
        '13': 'Down Fire',
        '14': 'Up Right Fire',
        '15': 'Up Left Fire',
        '16': 'Down Right Fire',
        '17': 'Down Left Fire',
    },
    'ChopperCommand-v5': {
        '0': 'None',
        '1': 'Fire',
        '2': 'Up',
        '3': 'Right',
        '4': 'Left',
        '5': 'Down',
        '6': 'Up Right',
        '7': 'Up Left',
        '8': 'Down Right',
        '9': 'Down Left',
        '10': 'Up Fire',
        '11': 'Right Fire',
        '12': 'Left Fire',
        '13': 'Down Fire',
        '14': 'Up Right Fire',
        '15': 'Up Left Fire',
        '16': 'Down Right Fire',
        '17': 'Down Left Fire',
    },
}
