_commit: v0.43.0
_src_path: gh:kitware-resonant/cookiecutter-resonant
core_app_name: core
include_example_code: false
project_name: MIXTAPE
project_slug: mixtape
python_package_name: mixtape
site_domain: demo.kitware.com
