# Generated by Django 5.1.6 on 2025-02-13 22:13

from django.db import migrations, models
import django.db.models.deletion

import mixtape.core.ray_utils.utility_functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_default_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('best', models.BooleanField(default=False)),
                ('last', models.BooleanField(default=False)),
                ('archive', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'environment',
                    models.CharField(
                        choices=[
                            ('knights_archers_zombies_v10', 'Pz Knightsarcherszombies'),
                            ('pistonball_v6', 'Pz Pistonball'),
                            ('cooperative_pong_v5', 'Pz Pong'),
                            ('BattleZone-v5', 'Gym Battlezone'),
                            ('Berzerk-v5', 'Gym Berzerk'),
                            ('ChopperCommand-v5', 'Gym Choppercommand'),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    'algorithm',
                    models.CharField(choices=[('PPO', 'Ppo'), ('DQN', 'Dqn')], max_length=200),
                ),
                ('parallel', models.BooleanField()),
                ('num_gpus', models.FloatField(default=0.0)),
                ('iterations', models.PositiveIntegerField(default=100)),
                ('config', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='InferenceRequest',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parallel', models.BooleanField()),
                ('config', models.JSONField()),
                (
                    'checkpoint',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.checkpoint'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'inference_request',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.inferencerequest'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
                (
                    'episode',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.episode'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='training_request',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='checkpoints',
                to='core.trainingrequest',
            ),
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('agent', models.CharField(max_length=200)),
                ('action', models.FloatField()),
                ('reward', models.FloatField()),
                (
                    'observation_space',
                    models.JSONField(
                        encoder=mixtape.core.ray_utils.utility_functions.NumpyJSONEncoder
                    ),
                ),
                (
                    'step',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.step'),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('agent', 'step'), name='unique_agent_step')
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='checkpoint',
            constraint=models.UniqueConstraint(
                fields=('training_request', 'best'), name='unique_checkpoint_best'
            ),
        ),
        migrations.AddConstraint(
            model_name='checkpoint',
            constraint=models.UniqueConstraint(
                fields=('training_request', 'last'), name='unique_checkpoint_last'
            ),
        ),
        migrations.AddConstraint(
            model_name='checkpoint',
            constraint=models.CheckConstraint(
                condition=models.Q(('best', True), ('last', True), _connector='OR'),
                name='best_or_last',
            ),
        ),
    ]
