# Generated by Django 5.1.6 on 2025-02-18 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentstep',
            name='step',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='agent_steps',
                to='core.step',
            ),
        ),
    ]
