# Generated by Django 5.1.6 on 2025-02-24 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_agentstep_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='episode',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.episode'
            ),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(
                fields=('episode', 'number'), name='unique_episode_number'
            ),
        ),
    ]
