# Generated by Django 5.1.6 on 2025-05-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_step_episode_step_unique_episode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inferencerequest',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='algorithm',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='environment',
            field=models.CharField(max_length=200),
        ),
        migrations.RenameModel(
            old_name='TrainingRequest',
            new_name='Training',
        ),
        migrations.RenameField(
            model_name='checkpoint',
            old_name='training_request',
            new_name='training',
        ),
        migrations.RenameModel(
            old_name='InferenceRequest',
            new_name='Inference',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='inference_request',
            new_name='inference',
        ),
        migrations.RemoveConstraint(
            model_name='checkpoint',
            name='unique_checkpoint_best',
        ),
        migrations.RemoveConstraint(
            model_name='checkpoint',
            name='unique_checkpoint_last',
        ),
        migrations.AddConstraint(
            model_name='checkpoint',
            constraint=models.UniqueConstraint(
                fields=('training', 'best'), name='unique_checkpoint_best'
            ),
        ),
        migrations.AddConstraint(
            model_name='checkpoint',
            constraint=models.UniqueConstraint(
                fields=('training', 'last'), name='unique_checkpoint_last'
            ),
        ),
        migrations.RemoveConstraint(
            model_name='checkpoint',
            name='best_or_last',
        ),
    ]
