# Generated by Django 5.1.6 on 2025-05-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trainingrequest_is_external_alter_checkpoint_archive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionMapping',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('environment', models.CharField(max_length=200)),
                ('mapping', models.JSONField()),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('environment',), name='unique_environment')
                ],
            },
        ),
    ]
