# Generated by Django 5.1.6 on 2025-05-02 19:11

from django.db import migrations, models

from mixtape.environments.mappings import action_maps


def create_default_action_mappings(apps, schema_editor):
    # Create the default action mappings for all of the environments we support
    action_mapping = apps.get_model('core', 'ActionMapping')
    for environment, mapping in action_maps.items():
        action_mapping.objects.create(
            environment=environment,
            mapping=mapping,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trainingrequest_is_external_alter_checkpoint_archive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionMapping',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('environment', models.CharField(max_length=200)),
                ('mapping', models.JSONField()),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('environment',), name='unique_environment')
                ],
            },
        ),
        migrations.RunPython(create_default_action_mappings),
    ]
