# Generated by Django 5.1.6 on 2025-05-15 17:25

from django.db import migrations, models

import mixtape.core.ray_utils.json_encoder


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_actionmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionmapping',
            name='mapping',
            field=models.JSONField(encoder=mixtape.core.ray_utils.json_encoder.CustomJSONEncoder),
        ),
        migrations.AlterField(
            model_name='inference',
            name='config',
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=mixtape.core.ray_utils.json_encoder.CustomJSONEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='training',
            name='config',
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=mixtape.core.ray_utils.json_encoder.CustomJSONEncoder,
                null=True,
            ),
        ),
    ]
