# Generated by Django 5.2.3 on 2025-07-21 14:58

from django.db import migrations, models

import mixtape.core.models.agent_step
import mixtape.core.ray_utils.json_encoder


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_actionmapping_mapping_alter_inference_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentstep',
            name='reward',
        ),
        migrations.AddField(
            model_name='agentstep',
            name='rewards',
            field=models.JSONField(
                default=mixtape.core.models.agent_step._rewards_default,
                encoder=mixtape.core.ray_utils.json_encoder.CustomJSONEncoder,
            ),
        ),
        migrations.AddField(
            model_name='training',
            name='reward_mapping',
            field=models.JSONField(
                blank=True, encoder=mixtape.core.ray_utils.json_encoder.CustomJSONEncoder, null=True
            ),
        ),
    ]
