# Generated by Django 5.2.3 on 2025-07-22 13:24

import mixtape.core.ray_utils.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_agentstep_reward_agentstep_rewards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstep',
            name='action_distribution',
            field=models.JSONField(blank=True, encoder=mixtape.core.ray_utils.json_encoder.CustomJSONEncoder, null=True),
        ),
    ]
