# Generated by Django 5.2.4 on 2025-10-27 13:40

from django.db import migrations, models
import django.db.models.deletion

import mixtape.core.models.episode_step


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agentstep_action_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstep',
            name='custom_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentstep',
            name='enemy_agent_health',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentstep',
            name='enemy_unit_health',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentstep',
            name='health',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentstep',
            name='predicted_reward',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentstep',
            name='value_estimate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UnitStep',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('action', models.FloatField()),
                (
                    'rewards',
                    models.JSONField(default=mixtape.core.models.episode_step._rewards_default),
                ),
                ('action_distribution', models.JSONField(blank=True, null=True)),
                ('health', models.FloatField(blank=True, null=True)),
                ('value_estimate', models.FloatField(blank=True, null=True)),
                ('predicted_reward', models.FloatField(blank=True, null=True)),
                ('custom_metrics', models.JSONField(blank=True, null=True)),
                ('unit', models.CharField(max_length=200)),
                (
                    'agent_step',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='unit_steps',
                        to='core.agentstep',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('agent_step', 'unit'), name='unique_unit_step')
                ],
            },
        ),
    ]
