# Generated by Django 5.2.4 on 2025-10-27 16:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agentstep_action_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringResult',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'feature_types',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ('observations', 'Observations'),
                                ('agent_outputs', 'Agent_Outputs'),
                                ('rewards', 'Rewards'),
                                ('states', 'States'),
                                ('actions', 'Actions'),
                            ],
                            max_length=20,
                        ),
                        size=None,
                    ),
                ),
                ('parameters', models.JSONField()),
                ('parameters_hash', models.CharField(db_index=True, max_length=64)),
                ('results', models.JSONField()),
                (
                    'status',
                    models.CharField(
                        choices=[('success', 'Success'), ('failed', 'Failed')],
                        default='success',
                        max_length=10,
                    ),
                ),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'episode',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clustering_results',
                        to='core.episode',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('episode', 'feature_types', 'parameters_hash'),
                        name='unique_episode_clustering_params',
                    )
                ],
            },
        ),
    ]
