# Generated by Django 5.2.4 on 2025-12-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_agentstep_custom_metrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstep',
            name='enemy_unit_steps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
