# Generated by Django 5.2.4 on 2025-12-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_clusteringresult'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checkpoint',
            name='unique_checkpoint_best',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='best',
        ),
        migrations.AlterField(
            model_name='inference',
            name='parallel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='training',
            name='parallel',
            field=models.BooleanField(default=False),
        ),
    ]
