# Generated by Django 5.2.4 on 2025-09-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_agentstep_custom_metrics_agentstep_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstep',
            name='enemy_agent_health',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentstep',
            name='enemy_unit_health',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='health',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitstep',
            name='health',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
